### ISSUE TITLE
Error while generating conformers

### ISSUE THREAD

**Issue by binary-alkemi** [durrantlab/gypsum_dl#1]
Hi,

I am using Gupsum-dl to generate the conformers from SDF files obtained from PubChem.

`run_gypsum_dl.py --source PubChem_similar_compounds.smi --output_folder gypsum_output/ --min_ph 7.4 --max_ph 7.4 --pka_precision 1  --use_durrant_lab_filters`

I am getting the following error. Is there any way to understand which molecule or step is causing an error?

```
RuntimeError: Pre-condition Violation
	bad bond type
	Violation occurred on line 121 in file Code/GraphMol/Canon.cpp
	Failed Expression: bond->getBondType() == Bond::SINGLE || bond->getIsAromatic()
	RDKIT: 2023.03.1
	BOOST: 1_78
```
Thanks in advance.

**Comment by jacobdurrant** [comment]
Thanks for reaching out about the error you encountered while using Gypsum-DL. Without having access to the actual SMILES file, it's challenging to pinpoint the exact cause of the error. But, based on the error message you provided, I suspect one of the SMILES strings is invalid.

To further investigate, would you mind sending me the SMILES file so I can try to debug? Otherwise, I recommend running the SMILES strings through Gypsum-DL in smaller batches to narrow down the problematic molecule and potentially identify the specific SMILES string causing the error. 

If you manage to identify the issue, please let me know! I might be able to update the code to handle this situation more gracefully.

Sorry for not being able to provide a more immediate solution!

All the best,

Jacob
